# Build catalog bundle — manifests/snapshot/models/**/*.json 들의 모든 entries를 단일
# manifests/apps/catalog.json 으로 합쳐 빌드.
#
# 정책 (Phase 13'.a — live model catalog refresh):
# - registry-fetcher가 "catalog" manifest_id로 단일 파일을 받음 (per-file fetch는 GitHub
#   rate limit 위험 + jsDelivr indexing 부재로 비현실).
# - dev 모드는 여전히 per-file 디렉터리에서 직접 로드 (lib.rs::load_bundled_catalog).
# - release 빌드 시점에 본 스크립트를 1회 실행 — 모든 entries가 catalog.json에 동기화됨.
# - manifest 추가/수정 후엔 반드시 본 스크립트 재실행.
#
# 사용:
#   pwsh ./.claude/scripts/build-catalog-bundle.ps1

$ErrorActionPreference = "Stop"

$repo = (Resolve-Path "$PSScriptRoot\..\..").Path
$src = "$repo\manifests\snapshot\models"
$dst = "$repo\manifests\apps\catalog.json"

if (-not (Test-Path $src)) {
  Write-Error "source 디렉터리가 없어요: $src"
  exit 1
}

# 모든 entries 수집 — 모든 *.json 파일 walk + entries 병합.
$entries = @()
$count = 0
Get-ChildItem -Path $src -Recurse -Filter *.json | ForEach-Object {
  $body = Get-Content $_.FullName -Raw | ConvertFrom-Json
  if ($body.schema_version -ne 1) {
    Write-Warning "schema_version != 1, skip: $($_.FullName)"
    return
  }
  if (-not $body.entries) {
    Write-Warning "entries 필드 없음, skip: $($_.FullName)"
    return
  }
  foreach ($e in $body.entries) {
    $entries += $e
    $count += 1
  }
}

Write-Output "수집된 entries: $count 개"

# 중복 id 검사 — fail.
$ids = $entries | ForEach-Object { $_.id }
$dup = $ids | Group-Object | Where-Object { $_.Count -gt 1 }
if ($dup) {
  Write-Error ("중복 id 발견: " + ($dup | ForEach-Object { $_.Name }) -join ", ")
  exit 1
}

# id 알파벳 순 — deterministic build.
$entries = $entries | Sort-Object id

# 출력 — 단일 ModelManifest 형식.
$bundle = [ordered]@{
  '$schema_hint' = "model-registry ModelManifest schema_version=1. Auto-generated by build-catalog-bundle.ps1 — do not edit by hand."
  schema_version = 1
  generated_at = (Get-Date -Format "yyyy-MM-ddTHH:mm:ssZ")
  entries = $entries
}

# UTF-8 (no BOM) — Rust serde_json이 BOM 거부할 수 있어요.
$json = $bundle | ConvertTo-Json -Depth 16
[System.IO.File]::WriteAllText($dst, $json, (New-Object System.Text.UTF8Encoding $false))

$msg = "OK: " + $dst + " entries=" + $count
Write-Output $msg
